USE [master]
GO

/****** Object:  Database [YH119]    Script Date: 2023/8/31 15:43:49 ******/
CREATE DATABASE [YH119]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'YH119', FILENAME = N'/mnt/0009DC270007488C/DBDATA/YH119.mdf' , SIZE = 120000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'YH119_log', FILENAME = N'/mnt/0009DC270007488C/DBDATA/YH119_log.ldf' , SIZE = 120000KB , MAXSIZE = 2048000KB , FILEGROWTH = 1024KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [YH119].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [YH119] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [YH119] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [YH119] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [YH119] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [YH119] SET ARITHABORT OFF 
GO

ALTER DATABASE [YH119] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [YH119] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [YH119] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [YH119] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [YH119] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [YH119] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [YH119] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [YH119] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [YH119] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [YH119] SET  DISABLE_BROKER 
GO

ALTER DATABASE [YH119] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [YH119] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [YH119] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [YH119] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [YH119] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [YH119] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [YH119] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [YH119] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [YH119] SET  MULTI_USER 
GO

ALTER DATABASE [YH119] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [YH119] SET DB_CHAINING OFF 
GO

ALTER DATABASE [YH119] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [YH119] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [YH119] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [YH119] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [YH119] SET QUERY_STORE = OFF
GO

ALTER DATABASE [YH119] SET  READ_WRITE 
GO


