CREATE DATABASE [YH120]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'YH120', FILENAME = N'/mnt/0009DC270007488C/DBDATA/YH120.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'YH120_log', FILENAME = N'/mnt/0009DC270007488C/DBDATA/YH120_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [YH120] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [YH120] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [YH120] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [YH120] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [YH120] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [YH120] SET ARITHABORT OFF 
GO
ALTER DATABASE [YH120] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [YH120] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [YH120] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [YH120] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [YH120] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [YH120] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [YH120] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [YH120] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [YH120] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [YH120] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [YH120] SET  DISABLE_BROKER 
GO
ALTER DATABASE [YH120] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [YH120] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [YH120] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [YH120] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [YH120] SET  READ_WRITE 
GO
ALTER DATABASE [YH120] SET RECOVERY FULL 
GO
ALTER DATABASE [YH120] SET  MULTI_USER 
GO
ALTER DATABASE [YH120] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [YH120] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [YH120] SET DELAYED_DURABILITY = DISABLED 
GO
USE [YH120]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [YH120]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [YH120] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
