CREATE DATABASE [DBCControl]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBCControl', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DBCControl.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DBCControl_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DBCControl_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE Chinese_PRC_CI_AS
GO
ALTER DATABASE [DBCControl] SET COMPATIBILITY_LEVEL = 90
GO
ALTER DATABASE [DBCControl] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBCControl] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBCControl] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBCControl] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBCControl] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBCControl] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBCControl] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [DBCControl] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBCControl] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBCControl] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBCControl] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBCControl] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBCControl] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBCControl] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBCControl] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBCControl] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DBCControl] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBCControl] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBCControl] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBCControl] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBCControl] SET  READ_WRITE 
GO
ALTER DATABASE [DBCControl] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DBCControl] SET  MULTI_USER 
GO
ALTER DATABASE [DBCControl] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBCControl] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [DBCControl]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DBCControl] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
